### ISSUE TITLE
icon.png is missing

### ISSUE THREAD

**Issue by suryagaddipati** [ALeoLeonard/touchbar-pomodoro#3]
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from icon.png
    at App.app.once (//touchbar-pomodoro/index.js:91:10)

```

**Comment by ALeoLeonard** [comment]
https://github.com/ALeoLeonard/touchbar-pomodoro/commit/fcb98980e0780855d4f371262cc93b06e5ecfc2b

**Comment by ALeoLeonard** [comment]
Thanks for opening this issue. I have uploaded the icon in the commit referenced above. Please let me know if this doesn't resolve the issue. Thanks again!
